In [1]:
# 쉬트라센 알고리즘

import numpy as np

def strassen(n, A, B, C):
    threshold = 2

    A11 = np.array([[A[rows][cols] for cols in range(n//2)]for rows in range(n//2)])
    A12 = np.array([[A[rows][cols] for cols in range(n//2,n)]for rows in range(n//2)])
    A21 = np.array([[A[rows][cols] for cols in range(n//2)]for rows in range(n//2,n)])
    A22 = np.array([[A[rows][cols] for cols in range(n//2,n)]for rows in range(n//2,n)])
    B11 = np.array([[B[rows][cols] for cols in range(n//2)]for rows in range(n//2)])
    B12 = np.array([[B[rows][cols] for cols in range(n//2,n)]for rows in range(n//2)])
    B21 = np.array([[B[rows][cols] for cols in range(n//2)]for rows in range(n//2,n)])
    B22 = np.array([[B[rows][cols] for cols in range(n//2,n)]for rows in range(n//2,n)])

    if (n <= threshold):
        C = np.array(A) @ np.array(B)
        
    else:
        M = np.array([])
        M1=strassen(n//2, (A11 + A22), (B11 + B22), M)
        M2=strassen(n//2, (A21 + A22), B11, M)
        M3=strassen(n//2, A11, (B12 - B22), M)
        M4=strassen(n//2, A22, (B21 - B11), M)
        M5=strassen(n//2, (A11 + A12), B22, M)
        M6=strassen(n//2, (A21 - A11), (B11 + B12), M)
        M7=strassen(n//2, (A12 - A22), (B21 + B22), M)

        C =  np.vstack([ np.hstack([M1 + M4 - M5 + M7, M3 + M5]), np.hstack([M2 + M4, M1 - M2 + M3 + M6]) ])
    
    return C


A=[ [-1,2,-3,-1], [1,-2,3,4], [0,2,-5,0],[1,2,7,1]]
B=[ [-2,2,3,3], [3,-1,3,0], [1,1,2,0],[4,2,-1,-1]]
C = np.array([])
C = strassen(4, A, B, C)
print(C)


[[ 1 -9 -2 -2]
 [11 15 -1 -1]
 [ 1 -7 -4  0]
 [15  9 22  2]]
